"""retention_metadata

Revision ID: ad2e9b6dd006
Revises: 0003_add_drug_knowledge
Create Date: 2026-06-29 17:03:30.045347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2e9b6dd006'
down_revision: Union[str, None] = '0003_add_drug_knowledge'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace_events', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trace_events', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('visit_summaries', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('visit_summaries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_summaries', 'deleted_at')
    op.drop_column('visit_summaries', 'expires_at')
    op.drop_column('trace_events', 'deleted_at')
    op.drop_column('trace_events', 'expires_at')
    # ### end Alembic commands ###

